[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/unity-demo/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' blob: data:; worker-src 'self' blob:; object-src 'self'; media-src 'self' blob:;"

[[headers]]
  for = "/unity-demo/Build/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/unity-demo/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"

[[headers]]
  for = "/unity-demo/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"

[[headers]]
  for = "/unity-demo/*.js.br"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Content-Encoding = "br"

[[headers]]
  for = "/unity-demo/*.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Force HTTPS redirect
[[redirects]]
  from = "http://chat-mass.com/*"
  to = "https://chat-mass.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.chat-mass.com/*"  
  to = "https://chat-mass.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 